server:
  port: 8088

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/t4?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    driverClassName: org.mariadb.jdbc.Driver
    username: chacha
    password: ckxowls1!

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  devtools:
    livereload:
      enabled: true